# Generated by Django 5.0.4 on 2026-09-08 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0002_cart_seller_alter_cart_user_alter_cartitem_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'seller'), name='unique_user_seller'),
        ),
    ]
