# Generated by Django 5.0.4 on 2026-10-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0004_order_address_order_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('order_shipped', 'Order Shipped')], default='new_order', max_length=64),
        ),
    ]
