# Generated by Django 5.0.4 on 2026-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='alt_text',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.ForeignKey> image', max_length=64, null=True),
        ),
    ]
